### ISSUE TITLE
Can't see setting bar

### ISSUE THREAD

**Issue by Synesthesya** [CookiePLMonster/SilentPatchCMR2#1]
Whenever I start a rally stage, I cannot see the bar related to the setting of the car, for example the type of tires I want to use. So, the game isn't playable in a competitive way.

**Comment by CookiePLMonster** [comment]
You're using an Intel GPU, yes? This is a known issue not related to the fix itself.

Use dgVoodoo with the game.

**Comment by CookiePLMonster** [comment]
No response and other people having the same problem solved it with dgVoodoo, so I am going to assume it helped.
