### ISSUE TITLE
Add Multiplayer support for the Silent Patch

### ISSUE THREAD

**Issue by Santiii733** [CookiePLMonster/SilentPatchCMR2#2]
Hey :), it's possible you make a multiplayer silentpatch?

Thx 👍

**Comment by CookiePLMonster** [comment]
While that's a reasonable suggestion, doesn't the 1.11 executable shipped with the patch work without a CD? I am fairly sure it does, and that was the only benefit of the Network EXE.

**Comment by Santiii733** [comment]
Ok, working with radmin VPN!
