### ISSUE TITLE
Crashes if I try and select 2160p resolution

### ISSUE THREAD

**Issue by daninthemix** [CookiePLMonster/SilentPatchCMR2#5]
I've left everything at default, so the game with SilentPatch is launching windowed borderless. I can select any resolution just fine, except my native desktop res - 2160p. If I set that the game crashes.

Any ideas?

**Comment by CookiePLMonster** [comment]
From what I know, it's a known limitation of DX7 and earlier, you just cannot use resolutions over 2048px width or height with them. Try to use [dgVoodoo2](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2/) with the game.

**Comment by daninthemix** [comment]
Thanks for the quick answer - the SilentPatched version works great at 4K with DgVoodoo!
